name:                calculations
version:             0.1.0.0
github:              "githubuser/calculations"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/calculations#readme>

dependencies:
- base >= 4.7 && < 5
- type-tensor
- singletons

library:
  source-dirs: src

executables:
  calculations-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - calculations
