resolver: lts-15.5

packages:
- .

extra-deps:
- git: https://github.com/nilsalex/type-tensor.git
  commit: 7190bd5d7598f6b41186bd33fe54fb7a8b4fd06c
- git: https://github.com/nilsalex/sparse-tensor.git
  commit: e72e9a60b5f0a5c8f944c1c4836b8d8e5419deb3
  subdirs:
    - package
