name:                ansaetze
version:             0.1.0.0
github:              "nilsalex/linear-algebra-lagrangian"
license:             MIT
author:              "Nils Alex"
maintainer:          "nils.alex@fau.de"
copyright:           "2002 Nils Alex"
category:            Math
synopsis:            Ansaetze and solutions for third-order area metric lagrangians

extra-source-files:
- README.md
- ChangeLog.md

description:         Ansaetze and solutions for third-order area metric lagrangians using
                     safe-tensor, safe-tensor-sparse-tensor-compat, and sparse-tensor.

dependencies:
- base >= 4.7 && < 5
- safe-tensor >=0.2.1
- safe-tensor-sparse-tensor-compat
- mtl
- containers
- hmatrix

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  ansaetze-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - ansaetze
