resolver: nightly-2020-07-19

packages:
- .

extra-deps:
- git: https://github.com/nilsalex/sparse-tensor.git
  commit: 6e1dbc8194c00e1a4aa29e86e65284740e8ace85
  subdirs:
    - package
- git: https://github.com/nilsalex/safe-tensor.git
  commit: e91e0c048650749053369dec8e6ab31628edd81d
  subdirs:
    - packages/safe-tensor
    - packages/safe-tensor-sparse-tensor-compat
